version: "3.9"
services:
  app:
    build: .
    container_name: crud_agenda_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  mongo:
    image: mongo:6
    container_name: crud_agenda_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: Agenda
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
