version: "3.9"
services:
  app:
    build: .
    container_name: usuarios_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: usuarios_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuariosdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: