CREATE TABLE IF NOT EXISTS usuarios (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(100) NOT NULL,
  CorreoElectronico VARCHAR(100) NOT NULL,
  FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'userpass';
FLUSH PRIVILEGES;